### ISSUE TITLE
Deleting dataset fails with code 403

### ISSUE THREAD

**Issue by fmcclean** [dafnifacility/user-feedback#87] opened 2021-06-18 13:47 UTC
![image](https://user-images.githubusercontent.com/17356802/122570825-05e24300-d044-11eb-8636-41764d6946e1.png)

**Comment by tg137** [comment] 2021-06-18 14:25
Thanks Fergus.

This is a problem with our workflow system. We're creating the link between the owner of the workflow and any dataset _versions_ that are produced but we're not creating the equivalent link for the _parent_ dataset. I think if you clicked "Delete dataset version" then this would succeed but we will add the link to the parent too so that both options work.

Captured at https://jira.dafni.rl.ac.uk/browse/CORE-1990

**Comment by tg137** [comment] 2021-06-18 14:46
Confirmed that the "Delete dataset version" button also doesn't work. This is probably because the dataset gets cleared up after the last version is deleted and the user doesn't have permission to do this final deletion.

**Comment by roseDickinson** [comment] 2021-07-13 12:16
This was fixed in v2.5.0 for any new Datasets that are created by Workflows. For any existing Datasets please feel free to message us and we'll delete them for you.

**Closed as completed by roseDickinson** 2021-07-13 12:16 UTC
Labels: bug, ingested
